name: Build and Deploy Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t sampledeploy:latest -f ./sampledeploy/Dockerfile .

    - name: Run container (deployment simulation)
      run: docker run -d --name sampledeploy -p 8080:80 sampledeploy:latest

    - name: Verify container is running
      run: docker ps -a

