name: .NET Build and Deploy with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t sampledeploy:latest ./sampledeploy

    - name: Run container
      run: docker run --rm sampledeploy:latest
